---
# Variables used in tasks:
# - openwrt_config_system (dict)

- name: Revert pending UCI changes
  uci:
    command: revert
    key: system
  when:
    - openwrt_config_system is defined

- name: Set system settings
  uci:
    command: section
    key: system.@system[0]
    type: system
    value:
      hostname: "{{ openwrt_config_system.hostname | default(inventory_hostname) }}"
      timezone: "{{ openwrt_config_system.timezone | default('UTC') }}"
      zonename: "{{ openwrt_config_system.zonename | default('UTC') }}"
      conloglevel: "{{ openwrt_config_system.conloglevel | default() }}"
      cronloglevel: "{{ openwrt_config_system.cronloglevel | default() }}"
      log_ip: "{{ openwrt_config_system.log_ip | default() }}"
      log_proto: "{{ openwrt_config_system.log_proto | default() }}"
  when: openwrt_config_system is defined

- name: Set NTP settings
  uci:
    command: section
    key: system.ntp
    type: timeserver
    value:
      enabled: "{{ openwrt_config_system.ntp.enabled | default(1) }}"
      enable_server: "{{ openwrt_config_system.ntp.enable_server | default(0) }}"
  when: openwrt_config_system.ntp is defined

# Separate section for NTP servers to avoid changing defaults in case custom are not set
- name: Set NTP servers
  uci:
    command: section
    key: system.ntp
    type: timeserver
    value:
      server: "{{ openwrt_config_system.ntp.servers }}"
  when: openwrt_config_system.ntp.servers is defined

- name: Commit UCI changes done
  uci:
    command: commit
  when:
    - openwrt_config_system is defined
  notify: Reload system settings
